//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public System.Guid ID { get; set; }
        public string Caption { get; set; }
        public string Text { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.Guid> GoodsID { get; set; }
        public Nullable<System.Guid> BillID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
    }
}
