//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public long UniqueID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> GoodsID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> NWeight { get; set; }
        public string Machine { get; set; }
        public Nullable<decimal> Cycle { get; set; }
        public Nullable<decimal> ManHour { get; set; }
        public Nullable<decimal> ErrorRate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Wages { get; set; }
        public Nullable<System.Guid> WageDesignID { get; set; }
        public Nullable<int> PlanYield { get; set; }
        public Nullable<int> Yielded { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public string Subject { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Label { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public string RecurrenceInfo { get; set; }
        public string ReminderInfo { get; set; }
        public string CustomField1 { get; set; }
        public int WageStatus { get; set; }
    }
}
