//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttGeneralLog
    {
        public System.Guid ID { get; set; }
        public string EnrollNumber { get; set; }
        public int VerifyMode { get; set; }
        public int InOutMode { get; set; }
        public System.DateTime AttTime { get; set; }
        public int Workcode { get; set; }
        public bool AttFlag { get; set; }
        public int AttStatus { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> SchClassID { get; set; }
    }
}
