//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public System.Guid GoodsID { get; set; }
        public System.Guid ParentGoodsID { get; set; }
        public decimal Qty { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
        public decimal Price { get; set; }
        public decimal PriceNoTax { get; set; }
        public int Type { get; set; }
        public decimal Discount { get; set; }
        public decimal OtherFee { get; set; }
        public string Remark { get; set; }
    }
}
