//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class ButtonPermission
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public System.Guid UserID { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Caption { get; set; }
    	[DataMember]
        public bool CheckBoxState { get; set; }
    }
}
