//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Contacts { get; set; }
        public string ContactTel { get; set; }
        public string ContactCellPhone { get; set; }
        public string QQ { get; set; }
        public string Fax { get; set; }
        public Nullable<int> AccountPeriod { get; set; }
        public int Type { get; set; }
        public string ACBank { get; set; }
        public string ACNo { get; set; }
        public string Tax { get; set; }
        public string InvoiceTitle { get; set; }
        public string InvoiceAddr { get; set; }
        public string InvoiceTel { get; set; }
        public int Status { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Remark { get; set; }
        public string LogisticsTel { get; set; }
        public string LogisticsAddress { get; set; }
    }
}
