//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class EMSGoodsTrackingDailyReport
    {
    	[DataMember]
        public string 委托厂商 { get; set; }
    	[DataMember]
        public System.DateTime 日期 { get; set; }
    	[DataMember]
        public string 货号 { get; set; }
    	[DataMember]
        public string 品名 { get; set; }
    	[DataMember]
        public Nullable<decimal> 应收货品数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本日发料数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本日交货数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 已用物料数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本日退料数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 未收货品数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 厂商存料数量 { get; set; }
    }
}
