//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.OrderDtl = new HashSet<OrderDtl>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public System.Guid GoodsTypeID { get; set; }
        public System.Guid PackagingID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> Dosage { get; set; }
        public Nullable<decimal> Subpackage { get; set; }
        public string Unit { get; set; }
        public string SPEC { get; set; }
        public string MEAS { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public decimal Price { get; set; }
        public decimal PriceNoTax { get; set; }
        public string BarCode { get; set; }
        public decimal Volume { get; set; }
        public decimal GWeight { get; set; }
        public decimal NWeight { get; set; }
        public Nullable<decimal> Cycle { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
        public decimal InPutVAT { get; set; }
        public decimal OutPutVAT { get; set; }
        public decimal UpperLimit { get; set; }
        public decimal LowerLimit { get; set; }
        public byte[] Pic { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public System.DateTime AddTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string MainMark { get; set; }
        public string SideMark { get; set; }
        public string InnerMark { get; set; }
        public decimal CavityNumber { get; set; }
        public string Toner { get; set; }
        public string Remark { get; set; }
        public bool IsStop { get; set; }
        public Nullable<int> Source { get; set; }
        public decimal Subsidy { get; set; }
        public Nullable<int> PlanYield { get; set; }
    
        public virtual GoodsType GoodsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDtl> OrderDtl { get; set; }
    }
}
