//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public System.Guid ID { get; set; }
        public System.Guid WarehouseID { get; set; }
        public int WarehouseType { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public Nullable<System.Guid> DeptID { get; set; }
        public System.Guid GoodsID { get; set; }
        public decimal Qty { get; set; }
        public string MEAS { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
        public decimal Price { get; set; }
        public decimal Discount { get; set; }
        public decimal OtherFee { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal NWeight { get; set; }
    }
}
