//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public int SerialNo { get; set; }
        public string Name { get; set; }
        public string Caption { get; set; }
        public string Subtitle { get; set; }
        public string Prefix { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public bool CheckBoxState { get; set; }
    }
}
