//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHd
    {
        public System.Guid ID { get; set; }
        public string BillNo { get; set; }
        public System.Guid WarehouseID { get; set; }
        public int WarehouseType { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string Contacts { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.Guid Maker { get; set; }
        public System.DateTime MakeDate { get; set; }
        public Nullable<System.Guid> Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string MainMark { get; set; }
        public string Remark { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public int BillType { get; set; }
        public Nullable<decimal> BillAMT { get; set; }
        public Nullable<decimal> UnReceiptedAMT { get; set; }
        public byte[] Pic { get; set; }
    }
}
