//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDtl
    {
        public System.Guid ID { get; set; }
        public System.Guid HdID { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public System.Guid GoodsID { get; set; }
        public decimal Qty { get; set; }
        public string MEAS { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
        public decimal Price { get; set; }
        public decimal PriceNoTax { get; set; }
        public decimal Discount { get; set; }
        public decimal OtherFee { get; set; }
        public string MainMark { get; set; }
        public string SideMark { get; set; }
        public string InnerMark { get; set; }
        public decimal NWeight { get; set; }
        public Nullable<decimal> Modulus { get; set; }
        public string Remark { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
