//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptBillDtl
    {
        public System.Guid ID { get; set; }
        public System.Guid HdID { get; set; }
        public System.Guid BillID { get; set; }
        public decimal BillAMT { get; set; }
        public decimal ReceiptedAMT { get; set; }
        public decimal UnReceiptedAMT { get; set; }
        public decimal LastReceiptedAMT { get; set; }
    }
}
