//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class StatementOfAccountMaterialToSupplierReport
    {
    	[DataMember]
        public System.Guid CompanyID { get; set; }
    	[DataMember]
        public string 料名 { get; set; }
    	[DataMember]
        public Nullable<decimal> 上期存料 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本期去料 { get; set; }
    	[DataMember]
        public Nullable<decimal> 存料合计 { get; set; }
    	[DataMember]
        public Nullable<decimal> 生产用料 { get; set; }
    	[DataMember]
        public Nullable<decimal> 损耗 { get; set; }
    	[DataMember]
        public Nullable<decimal> 用料合计 { get; set; }
    	[DataMember]
        public Nullable<decimal> 结存 { get; set; }
    }
}
