//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class StatementOfAccountBasketToSupplierReport
    {
    	[DataMember]
        public System.Guid CompanyID { get; set; }
    	[DataMember]
        public string 筐类 { get; set; }
    	[DataMember]
        public Nullable<int> 上期欠筐 { get; set; }
    	[DataMember]
        public Nullable<int> 本期去筐 { get; set; }
    	[DataMember]
        public Nullable<int> 本期来筐 { get; set; }
    	[DataMember]
        public Nullable<int> 共欠 { get; set; }
    }
}
