//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class StatementOfAccountSummaryToSupplierReport
    {
    	[DataMember]
        public string 厂家代码 { get; set; }
    	[DataMember]
        public string 厂家名称 { get; set; }
    	[DataMember]
        public string 货号 { get; set; }
    	[DataMember]
        public string 品名 { get; set; }
    	[DataMember]
        public string 用料 { get; set; }
    	[DataMember]
        public Nullable<decimal> 数量 { get; set; }
    	[DataMember]
        public string 单位 { get; set; }
    	[DataMember]
        public Nullable<decimal> 模重 { get; set; }
    	[DataMember]
        public Nullable<decimal> 模数 { get; set; }
    	[DataMember]
        public Nullable<decimal> 单价 { get; set; }
    	[DataMember]
        public Nullable<decimal> 折扣 { get; set; }
    	[DataMember]
        public Nullable<decimal> 额外费用 { get; set; }
    	[DataMember]
        public Nullable<decimal> 金额 { get; set; }
    	[DataMember]
        public string 备注 { get; set; }
    }
}
