//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocktaking
    {
        public string Warehouse { get; set; }
        public int WarehouseType { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public int GoodsBigType { get; set; }
        public string Goods { get; set; }
        public decimal Qty { get; set; }
        public int PCS { get; set; }
        public string MEAS { get; set; }
        public string Checker { get; set; }
        public System.DateTime CheckingDate { get; set; }
    }
}
