//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOutBillDtl
    {
        public System.Guid ID { get; set; }
        public System.Guid HdID { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public System.Guid GoodsID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string MEAS { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<int> InnerBox { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal PriceNoTax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public Nullable<decimal> NWeight { get; set; }
        public string Remark { get; set; }
        public decimal TonsQty { get; set; }
        public decimal TonsPrice { get; set; }
    }
}
