//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemInfo
    {
        public string Company { get; set; }
        public int CompanyType { get; set; }
        public string Contracts { get; set; }
        public string Accounts { get; set; }
        public string FtpPath { get; set; }
        public string ServerUserName { get; set; }
        public string ServerPassword { get; set; }
        public string Version { get; set; }
    }
}
