//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> DeptID { get; set; }
        public string Post { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public string DormNo { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public string Permissions { get; set; }
        public string Remark { get; set; }
        public string AttCardnumber { get; set; }
        public int AttPrivilege { get; set; }
        public bool AttEnabled { get; set; }
        public int WageType { get; set; }
        public decimal Wages { get; set; }
        public decimal SchClassWage { get; set; }
        public decimal TimeWage { get; set; }
        public bool IsDel { get; set; }
    }
}
