//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class VAttGeneralLog
    {
    	[DataMember]
        public byte[] 照片 { get; set; }
    	[DataMember]
        public string 账号 { get; set; }
    	[DataMember]
        public string 姓名 { get; set; }
    	[DataMember]
        public string 部门 { get; set; }
    	[DataMember]
        public string 职位 { get; set; }
    	[DataMember]
        public System.DateTime 出勤时间 { get; set; }
    	[DataMember]
        public string 卡号 { get; set; }
    	[DataMember]
        public int 特权 { get; set; }
    	[DataMember]
        public int 验证方式 { get; set; }
    }
}
