//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAttAppointments
    {
        public long UniqueID { get; set; }
        public Nullable<System.Guid> GLogStartID { get; set; }
        public Nullable<System.Guid> GLogEndID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string 工号 { get; set; }
        public string 姓名 { get; set; }
        public int 工资状态 { get; set; }
        public string 年月 { get; set; }
        public Nullable<System.DateTime> 日期 { get; set; }
        public string 时段 { get; set; }
        public int SchSerialNo { get; set; }
        public Nullable<System.DateTime> 上班时间 { get; set; }
        public Nullable<System.DateTime> 下班时间 { get; set; }
        public Nullable<System.DateTime> 签到时间 { get; set; }
        public Nullable<System.DateTime> 签退时间 { get; set; }
        public int 考勤状态 { get; set; }
        public Nullable<int> 迟到分钟数 { get; set; }
        public Nullable<int> 早退分钟数 { get; set; }
        public string 备注 { get; set; }
    }
}
