//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAttWageBill
    {
        public System.Guid ID { get; set; }
        public System.Guid HdID { get; set; }
        public string 工资单号 { get; set; }
        public System.DateTime 结算日期 { get; set; }
        public int 状态 { get; set; }
        public string 年月 { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string 工号 { get; set; }
        public string 姓名 { get; set; }
        public Nullable<int> 班次 { get; set; }
        public Nullable<int> 迟到分钟数 { get; set; }
        public Nullable<int> 早退分钟数 { get; set; }
        public Nullable<int> 迟到次数 { get; set; }
        public Nullable<int> 早退次数 { get; set; }
        public Nullable<int> 旷工 { get; set; }
        public Nullable<int> 忘打卡 { get; set; }
        public Nullable<int> 请假 { get; set; }
        public decimal 基本工资 { get; set; }
        public decimal 福利 { get; set; }
        public decimal 扣款 { get; set; }
        public decimal 代扣社保 { get; set; }
        public decimal 代扣个税 { get; set; }
        public decimal 实发工资 { get; set; }
        public string 制单人 { get; set; }
        public System.DateTime 制单日期 { get; set; }
        public string 审核人 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public string 备注 { get; set; }
    }
}
