//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCompany
    {
        public System.Guid ID { get; set; }
        public string 代码 { get; set; }
        public string 名称 { get; set; }
        public int 客户类型 { get; set; }
        public Nullable<int> 账期 { get; set; }
        public Nullable<decimal> 欠款 { get; set; }
        public string 地址 { get; set; }
        public string 邮编 { get; set; }
        public string 联系人 { get; set; }
        public string 联系电话 { get; set; }
        public string 联系手机 { get; set; }
        public string QQ { get; set; }
        public string 传真 { get; set; }
        public string 物流地址 { get; set; }
        public string 物流电话 { get; set; }
        public string 开户行 { get; set; }
        public string 帐号 { get; set; }
        public string 税号 { get; set; }
        public string 开票抬头 { get; set; }
        public string 开票地址 { get; set; }
        public string 开票电话 { get; set; }
        public string 备注 { get; set; }
        public Nullable<bool> CheckBoxID { get; set; }
    }
}
