//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCustomerSettlement
    {
        public string 收款单号 { get; set; }
        public System.DateTime 收款日期 { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public string 客户 { get; set; }
        public Nullable<decimal> 上期结欠 { get; set; }
        public Nullable<decimal> 本期收款 { get; set; }
        public Nullable<decimal> 共欠 { get; set; }
        public Nullable<decimal> 本期结款 { get; set; }
        public Nullable<decimal> 本期结欠 { get; set; }
    }
}
