//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCustomerSalesReceiptedSummary
    {
        public string 客户代码 { get; set; }
        public string 客户名称 { get; set; }
        public Nullable<int> 客户类型 { get; set; }
        public string 联系人 { get; set; }
        public System.DateTime 交货日期 { get; set; }
        public Nullable<decimal> 箱数 { get; set; }
        public Nullable<decimal> 总数量 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public Nullable<decimal> 已收金额 { get; set; }
        public Nullable<decimal> 未收金额 { get; set; }
    }
}
