//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract]
    
    public partial class VFSMOrderDtlByMoldMaterial
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public System.Guid HdID { get; set; }
    	[DataMember]
        public System.Guid GoodsID { get; set; }
    	[DataMember]
        public System.Guid ParentGoodsID { get; set; }
    	[DataMember]
        public Nullable<decimal> Qty { get; set; }
    	[DataMember]
        public int PCS { get; set; }
    	[DataMember]
        public int InnerBox { get; set; }
    	[DataMember]
        public decimal Price { get; set; }
    	[DataMember]
        public decimal PriceNoTax { get; set; }
    	[DataMember]
        public decimal Discount { get; set; }
    	[DataMember]
        public decimal OtherFee { get; set; }
    	[DataMember]
        public int Type { get; set; }
    }
}
