//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGoodsBySLSalePrice
    {
        public Nullable<System.Guid> GoodsID { get; set; }
        public System.Guid ID { get; set; }
        public string 货号 { get; set; }
        public string 品名 { get; set; }
        public decimal 单价 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 外箱规格 { get; set; }
        public int Type { get; set; }
    }
}
