//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMaterial
    {
        public System.Guid ID { get; set; }
        public byte[] 图片 { get; set; }
        public string 货号 { get; set; }
        public string 品名 { get; set; }
        public string 货品类型 { get; set; }
        public decimal 单价 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public decimal 净重 { get; set; }
        public decimal 一出几 { get; set; }
        public string 条形码 { get; set; }
        public string 备注 { get; set; }
        public int Type { get; set; }
        public bool 停产 { get; set; }
        public Nullable<int> Source { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
    }
}
