//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOrderDtlByBOM
    {
        public Nullable<System.Guid> ID { get; set; }
        public System.Guid HdID { get; set; }
        public System.Guid GoodsID { get; set; }
        public Nullable<System.Guid> ParentGoodsID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> Shortage { get; set; }
        public decimal Yielded { get; set; }
        public decimal NWeight { get; set; }
        public Nullable<decimal> Counts { get; set; }
        public Nullable<decimal> Modulus { get; set; }
        public int Type { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
        public decimal Price { get; set; }
        public decimal PriceNoTax { get; set; }
        public decimal Discount { get; set; }
        public decimal OtherFee { get; set; }
        public string 货号 { get; set; }
        public string 品名 { get; set; }
        public int 货品大类 { get; set; }
        public string 规格 { get; set; }
        public string 单位 { get; set; }
        public decimal 一出几 { get; set; }
        public Nullable<int> Source { get; set; }
    }
}
