//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract]
    
    public partial class VOrder
    {
    	[DataMember]
        public System.Guid HdID { get; set; }
    	[DataMember]
        public string 订货单号 { get; set; }
    	[DataMember]
        public System.DateTime 订货日期 { get; set; }
    	[DataMember]
        public System.DateTime 交货日期 { get; set; }
    	[DataMember]
        public int 状态 { get; set; }
    	[DataMember]
        public string 客户代码 { get; set; }
    	[DataMember]
        public string 客户名称 { get; set; }
    	[DataMember]
        public Nullable<int> 客户类型 { get; set; }
    	[DataMember]
        public int 仓库类型 { get; set; }
    	[DataMember]
        public string 货号 { get; set; }
    	[DataMember]
        public string 正唛 { get; set; }
    	[DataMember]
        public string 品名 { get; set; }
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public decimal 箱数 { get; set; }
    	[DataMember]
        public decimal 发货数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 未送数量 { get; set; }
    	[DataMember]
        public int 装箱数 { get; set; }
    	[DataMember]
        public int 内盒 { get; set; }
    	[DataMember]
        public Nullable<decimal> 总数量 { get; set; }
    	[DataMember]
        public decimal 单价 { get; set; }
    	[DataMember]
        public decimal 折扣 { get; set; }
    	[DataMember]
        public decimal 额外费用 { get; set; }
    	[DataMember]
        public Nullable<decimal> 金额 { get; set; }
    	[DataMember]
        public string 包装方式 { get; set; }
    	[DataMember]
        public string 货品类型代码 { get; set; }
    	[DataMember]
        public string 货品类型名称 { get; set; }
    	[DataMember]
        public string 单位 { get; set; }
    	[DataMember]
        public string 规格 { get; set; }
    	[DataMember]
        public string 外箱规格 { get; set; }
    	[DataMember]
        public decimal 体积 { get; set; }
    	[DataMember]
        public decimal 毛重 { get; set; }
    	[DataMember]
        public decimal 净重 { get; set; }
    	[DataMember]
        public string 联系人 { get; set; }
    	[DataMember]
        public string 仓库 { get; set; }
    	[DataMember]
        public int 订单类型 { get; set; }
    	[DataMember]
        public int 类型 { get; set; }
    	[DataMember]
        public string 制单人 { get; set; }
    	[DataMember]
        public System.DateTime 制单日期 { get; set; }
    	[DataMember]
        public string 审核人 { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> 审核日期 { get; set; }
    	[DataMember]
        public string 备注 { get; set; }
    	[DataMember]
        public Nullable<int> SerialNo { get; set; }
    	[DataMember]
        public System.Guid GoodsID { get; set; }
    }
}
