//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VParentGoodsByBOM
    {
        public Nullable<System.Guid> ID { get; set; }
        public string 货号 { get; set; }
        public string 品名 { get; set; }
        public Nullable<decimal> 单价 { get; set; }
        public Nullable<decimal> 去税单价 { get; set; }
        public Nullable<int> 装箱数 { get; set; }
        public Nullable<int> 内盒 { get; set; }
        public string 单位 { get; set; }
        public string 外箱规格 { get; set; }
        public string 规格 { get; set; }
        public int 类型 { get; set; }
        public string 备注 { get; set; }
    }
}
