//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPaymentBillDtl
    {
        public Nullable<bool> CheckItem { get; set; }
        public System.Guid BillID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<System.Guid> SupplierID { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public int Type { get; set; }
        public Nullable<decimal> BillAMT { get; set; }
        public Nullable<decimal> PaidAMT { get; set; }
        public Nullable<decimal> UnPaidAMT { get; set; }
        public Nullable<decimal> LastPaidAMT { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> Worker { get; set; }
    }
}
