//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPO
    {
        public System.Guid HdID { get; set; }
        public string 订货单号 { get; set; }
        public System.DateTime 订货日期 { get; set; }
        public System.DateTime 交货日期 { get; set; }
        public int 状态 { get; set; }
        public string 供应商 { get; set; }
        public System.Guid ID { get; set; }
        public string 货号 { get; set; }
        public string 正唛 { get; set; }
        public string 品名 { get; set; }
        public decimal 数量 { get; set; }
        public decimal 到货数量 { get; set; }
        public Nullable<decimal> 未到数量 { get; set; }
        public decimal 单价 { get; set; }
        public decimal 额外费用 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 联系人 { get; set; }
        public string 仓库 { get; set; }
        public int 订单类型 { get; set; }
        public int 类型 { get; set; }
        public string 货品类型代码 { get; set; }
        public string 货品类型名称 { get; set; }
        public string 单位 { get; set; }
        public string 规格 { get; set; }
        public string 制单人 { get; set; }
        public System.DateTime 制单日期 { get; set; }
        public string 审核人 { get; set; }
        public Nullable<System.DateTime> 审核日期 { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public System.Guid GoodsID { get; set; }
    }
}
