//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class VProfitAndLoss
    {
    	[DataMember]
        public System.Guid WarehouseID { get; set; }
    	[DataMember]
        public int 仓库类型 { get; set; }
    	[DataMember]
        public Nullable<System.Guid> SupplierID { get; set; }
    	[DataMember]
        public System.Guid GoodsID { get; set; }
    	[DataMember]
        public string 仓库 { get; set; }
    	[DataMember]
        public string 盘点厂商 { get; set; }
    	[DataMember]
        public int 货品大类 { get; set; }
    	[DataMember]
        public string 货号 { get; set; }
    	[DataMember]
        public string 品名 { get; set; }
    	[DataMember]
        public Nullable<decimal> 盘点数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 库存数量 { get; set; }
    	[DataMember]
        public Nullable<decimal> 盈亏数量 { get; set; }
    	[DataMember]
        public int 装箱数 { get; set; }
    	[DataMember]
        public string 外箱规格 { get; set; }
    	[DataMember]
        public int 内盒 { get; set; }
    	[DataMember]
        public decimal 单价 { get; set; }
    }
}
