//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class VStatementOfAccountToCustomer
    {
    	[DataMember]
        public string 客户代码 { get; set; }
    	[DataMember]
        public string 客户名称 { get; set; }
    	[DataMember]
        public Nullable<int> 客户类型 { get; set; }
    	[DataMember]
        public string 结算类型 { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> 单据日期 { get; set; }
    	[DataMember]
        public string 货号 { get; set; }
    	[DataMember]
        public string 正唛 { get; set; }
    	[DataMember]
        public string 品名 { get; set; }
    	[DataMember]
        public Nullable<decimal> 箱数 { get; set; }
    	[DataMember]
        public int 装箱数 { get; set; }
    	[DataMember]
        public int 内盒 { get; set; }
    	[DataMember]
        public Nullable<decimal> 总数量 { get; set; }
    	[DataMember]
        public string 单位 { get; set; }
    	[DataMember]
        public decimal 单价 { get; set; }
    	[DataMember]
        public decimal 折扣 { get; set; }
    	[DataMember]
        public decimal 额外费用 { get; set; }
    	[DataMember]
        public string 包装方式 { get; set; }
    	[DataMember]
        public string 货品类型代码 { get; set; }
    	[DataMember]
        public string 货品类型名称 { get; set; }
    	[DataMember]
        public string 规格 { get; set; }
    	[DataMember]
        public string 外箱规格 { get; set; }
    	[DataMember]
        public decimal 体积 { get; set; }
    	[DataMember]
        public decimal 毛重 { get; set; }
    	[DataMember]
        public decimal 净重 { get; set; }
    }
}
