//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStockOutBillDtlByBOM
    {
        public System.Guid ID { get; set; }
        public System.Guid HdID { get; set; }
        public System.Guid GoodsID { get; set; }
        public System.Guid ParentGoodsID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public int PCS { get; set; }
        public int InnerBox { get; set; }
        public decimal Price { get; set; }
        public decimal PriceNoTax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public decimal BOMQty { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialUnit { get; set; }
        public Nullable<decimal> GoodsQty { get; set; }
        public string GoodsUnit { get; set; }
        public Nullable<decimal> Subpackage { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public string Material { get; set; }
        public Nullable<decimal> Mod { get; set; }
        public Nullable<decimal> TotalMod { get; set; }
        public Nullable<decimal> NWeight { get; set; }
    }
}
