//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class VSupplierSettlement
    {
    	[DataMember]
        public string 付款单号 { get; set; }
    	[DataMember]
        public System.DateTime 付款日期 { get; set; }
    	[DataMember]
        public Nullable<System.Guid> SupplierID { get; set; }
    	[DataMember]
        public string 供应商 { get; set; }
    	[DataMember]
        public Nullable<decimal> 上期结欠 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本期付款 { get; set; }
    	[DataMember]
        public Nullable<decimal> 共欠 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本期结款 { get; set; }
    	[DataMember]
        public Nullable<decimal> 本期结欠 { get; set; }
    }
}
