//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class WageBillDtl
    {
        public System.Guid ID { get; set; }
        public System.Guid HdID { get; set; }
        public string YearMonth { get; set; }
        public decimal Wages { get; set; }
        public decimal Welfare { get; set; }
        public decimal Deduction { get; set; }
        public decimal SocialSecurity { get; set; }
        public decimal IndividualIncomeTax { get; set; }
        public decimal AMT { get; set; }
    }
}
